name: newsletter
version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-newsletter}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
