app:
  port: 8000
  host: "127.0.0.1"

database:
  name: "newsletter"
  username: "postgres"
  password: "postgres"
  host: "127.0.0.1"
  port: 5432
  require_ssl: false

email_client:
  api_key: ""
  base_url: "localhost"
  sender: "test@test.com"
  sandbox: true
  timeout_millis: 10000
