name: zero2prod

# https://www.digitalocean.com/docs/platform/availability-matrix/
region: sgp

services:
  - name: zero2prod
    # Relative to the repository root
    dockerfile_path: Server.Dockerfile
    source_dir: .

    github:
      branch: main
      deploy_on_push: true
      repo: aboqasem/zero2prod

    health_check:
      http_path: /health

    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs

    routes:
      - path: /

    envs:
      - key: APP_DATABASE__HOST
        scope: RUN_TIME
        value: ${newsletter.HOSTNAME}
      - key: APP_DATABASE__PORT
        scope: RUN_TIME
        value: ${newsletter.PORT}
      - key: APP_DATABASE__NAME
        scope: RUN_TIME
        value: ${newsletter.DATABASE}
      - key: APP_DATABASE__USERNAME
        scope: RUN_TIME
        value: ${newsletter.USERNAME}
      - key: APP_DATABASE__PASSWORD
        scope: RUN_TIME
        value: ${newsletter.PASSWORD}

databases:
  - engine: PG
    name: newsletter
    production: true
    cluster_name: db-postgresql-sgp1-zero2prod-newsletter
    num_nodes: 1
    size: db-s-dev-database
    version: "15"
